Unmatching parentheses
Just a little fix because this unclosed parentheses rize an error in log file :

ERROR: unmatched parentheses in Container(9031).ListItem((2).Art(poster)